options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auth-service', '.']

  # Step 2: Push image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auth-service']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔐 Fetching JWT_SECRET from Secret Manager..."
        JWT_SECRET=$(gcloud secrets versions access latest --secret=JWT_SECRET)
        JWT_EXPIRES_IN=$(gcloud secrets versions access latest --secret=JWT_EXPIRES_IN)

        echo "🚀 Deploying to Cloud Run..."
        gcloud run deploy auth-service \
          --image gcr.io/$PROJECT_ID/auth-service \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars "JWT_SECRET=${JWT_SECRET},JWT_EXPIRES_IN=${JWT_EXPIRES_IN}"
